version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tier-list-image-upload-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wrm3yf5oc4gc"
s3_prefix = "tier-list-image-upload-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
